name: matrix_invite_backend
description: Backend for matrix-invite-code
version: 0.1.0
homepage: https://github.com/refi64/matrix-invite-code

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  checked_yaml: ^1.0.2
  corsac_jwt: ^0.2.2
  convert: ^2.1.1
  crypto: ^2.1.5
  dio: ^3.0.9
  fixnum: ^0.10.11
  get_it: ^4.0.2
  grpc: ^2.1.3
  injectable: ^0.4.0
  logger: ^0.9.1
  json_annotation: ^3.0.1
  hive: ^1.4.1
  random_string: ^2.0.1
  stack_trace: ^1.9.3
  synchronized: ^2.2.0

  matrix_invite_common:
    path: ../common

dev_dependencies:
  build_runner: ^1.10.0
  hive_generator: ^0.7.0
  injectable_generator: ^0.4.1
  pedantic: ^1.9.0
  json_serializable: ^3.3.0

dependency_overrides:
  injectable_generator:
    git:
      url: https://github.com/refi64/injectable
      ref: core-imports
      path: injectable_generator
