name: matrix_invite_common
description: Common files for matrix-invite-code
version: 0.1.0
homepage: https://github.com/refi64/matrix-invite-code

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  grpc: ^2.1.3
  logger: ^0.9.1
  protobuf: ^0.13.16
  stack_trace: ^1.9.3

dev_dependencies:
  grinder: ^0.8.4
  path: ^1.7.0
  pedantic: ^1.9.0
  protoc_plugin: ^17.0.5
